site_name: Calculation Docs

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - reference/calculations.md
    - reference/other.md
    - Third:
        - reference/third.md
  - explanation.md
